version: '2'
<<<<<<< HEAD
services:
  students-db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arquisoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: students
      MYSQL_HOST: students-db
  students-ms:
    build: .
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 4000 -b '0.0.0.0'"
    ports:
      - "4000:4000"
    depends_on:
      - students-db
=======
    services:
      students-db:
        image: mysql
        ports:
          - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: 123
          MYSQL_USER: arquisoft
          MYSQL_PASSWORD: 123
          MYSQL_DATABASE: students
          MYSQL_HOST: students-db
      students-ms:
        image: pcberriop/sa-students-ms
        command: bash -c "sleep 160 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 4000 -b '0.0.0.0'"
        ports:
        - '4000:4000'
        environment:
          PORT: '4000'
        depends_on:
          - students-db
>>>>>>> d38d26a3b85e3c7d5de3f5278b3509f5dd6b3532
