version: '2'
services:
  students-db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      HOST: 35.190.173.97
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arquisoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: students
      MYSQL_HOST: students-db
  students-ms:
    image: pcberriop/sa-students-ms
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 4000 -b '0.0.0.0'"
    ports:
      - "4000:4000"
    environment:
      - HOST: 35.190.173.97
      - PORT: '4000'
    depends_on:
      - students-db


